modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="arcane"
version="1.0.0-alpha"
displayName="Arcane"
logoFile="arcane.png"
authors="ZestyBlaze, Elysia"
credits="Thank you to Clover for helping us to make this mod as realistic as possible!"
description='''
Development Magic Mod
'''
[[dependencies.arcane]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcane]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
